apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-server
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: app-main
  source:
    repoURL: http://host.minikube.internal:3780/root/k8s-manifest.git
    targetRevision: main
    path: "applications/nodejs-server"
    # credentials:
    #   name: github-token-secret
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
