apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-example
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: app-example
  template:
    metadata:
      labels:
        app: app-example
    spec:
      containers:
      - image: docker.io/library/app-example:first
        name: app-example
        ports:
        - containerPort: 3770
