apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-server
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nodejs-server
  template:
    metadata:
      labels:
        app: nodejs-server
    spec:
      containers:
      - image: docker.io/library/nodejs-server:first
        name: nodejs-server
        ports:
        - containerPort: 3770
